### ISSUE TITLE
How to choose the value of m_e2weight?

### ISSUE THREAD

**Issue by Po-Ting-lin** [zjxeditor/LazySnapping#2]
Hi,

Thank you for sharing this implementation. 
How to choose the value of m_e2weight?
m_e2weight seems to influence greatly on maxflow. 
What's the consequence when using big or small value of m_e2weight?

Lin

**Comment by zjxeditor** [comment]
There is more detail information in the original paper for the meaning and role of E2Weight. The paper is public http://home.cse.ust.hk/~cktang/sample_pub/lazy_snapping.pdf, you can dive into it for some deep comprehension.

**Comment by Po-Ting-lin** [comment]
OK, got it. Thanks.
